name: build

on:
  workflow_call:

env:
  FIRMWARE_PATH: keyboards/bbrfkr/chasma

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: install qmk
        run: pip install qmk
      - name: setup qmk
        run: qmk setup -y -H ../qmk_firmware
      - name: replace soruce code
        run: >
          rm -rf ../qmk_firmware/$FIRMWARE_PATH &&
          cp -r firmware/qmk/chasma ../qmk_firmware/$FIRMWARE_PATH
      - name: build firmware
        run: >
          cd ../qmk_firmware &&
          qmk compile -kb bbrfkr/chasma -km via &&
          cd -
      - name: gather artifacts
        run: >
          mkdir artifacts &&
          cp ../qmk_firmware/.build/bbrfkr_chasma_via.hex firmware/via/chasma.json artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: ./artifacts/*
